# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-18 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20171213_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('kcjg', '\u8bfe\u7a0b\u673a\u6784'), ('gx', '\u9ad8\u6821'), ('gr', '\u4e2a\u4eba')], default='kcjg', max_length=100, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
